# Books mapping

"get:/books":
  description: "List all books by specified filters"
  resource: \Forest\Resources\Books
  action: getBooks
  role: "user"
  parameters:
    required:
      title: string
    optionals:
      year: integer
