#!/usr/bin/env php
<?php

require_once __DIR__ . '/src/Forest/Bootstrap.php';

$forest = new Forest\Bootstrap();

use Symfony\Component\Console\Application;

$application = new Application(
    $forest->getKernel()->getName(),
    $forest->getKernel()->getVersion()
);

$application->run();