#!/usr/bin/env php
<?php

require_once __DIR__ . '/src/Forest/Bootstrap.php';

$forest = new Forest\Bootstrap();

$application = new Forest\Bundle\Console\Application(
    $forest->getKernel()->getName(),
    $forest->getKernel()->getVersion()
);

$application->run();
